# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64a521d23c0c7a9514a94fd7be57c74e6e0a1d01da1de534ec8f1d984124323a3c80b83f29ce0a6d02347b4b3be7c0bc86910a9c9c7e1300a02c9d1a6251cc02

test:
  secret_key_base: 57aadbf81ecd5f4ccc6b657dcc29de9d2126340a07fbabf2dd399998660341da136b51af4a4728f3c37ec870957ba9c9effcc98e490b6dfb6391abd40b681c0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
