class CreateRecipes < ActiveRecord::Migration[5.0]
  def change
    create_table :recipes do |t|
      t.string :name
      t.string :description
      t.string :source
      t.string :category
      t.string :prep_time
      t.string :servings
      t.string :cals_serving
      t.binary :attachments
      t.string :notes
      t.string :ingredient1
      t.string :ingredient2
      t.string :ingredient3
      t.string :ingredient4
      t.string :ingredient5
      t.string :ingredient6
      t.string :ingredient7
      t.string :ingredient8
      t.string :ingredient9
      t.string :ingredient10
      t.string :ingredient11
      t.string :ingredient12
      t.string :ingredient13
      t.string :ingredient14
      t.string :ingredient15
      t.string :ingredient16
      t.string :ingredient17
      t.string :ingredient18
      t.string :ingredient19
      t.string :ingredient20
      t.string :ingredient21
      t.string :ingredient22
      t.integer :quantity1
      t.integer :quantity2
      t.integer :quantity3
      t.integer :quantity4
      t.integer :quantity5
      t.integer :quantity6
      t.integer :quantity7
      t.integer :quantity8
      t.integer :quantity9
      t.integer :quantity10
      t.integer :quantity11
      t.integer :quantity12
      t.integer :quantity13
      t.integer :quantity14
      t.integer :quantity15
      t.integer :quantity16
      t.integer :quantity17
      t.integer :quantity18
      t.integer :quantity19
      t.integer :quantity20
      t.integer :quantity21
      t.integer :quantity22
      t.text :instruction1
      t.text :instruction2
      t.text :instruction3
      t.text :instruction4
      t.text :instruction5
      t.text :instruction6
      t.text :instruction7
      t.text :instruction8
      t.text :instruction9
      t.text :instruction10
      t.text :instruction11
      t.text :instruction12
      t.text :instruction13
      t.text :instruction14
      t.text :instruction15
      t.text :instruction16
      t.text :instruction17
      t.text :instruction18
      t.text :instruction19
      t.text :instruction20

      t.timestamps
    end
  end
end
